### ISSUE TITLE
Tagging a release

### ISSUE THREAD

**Issue by Zopieux** [mhansen/rtl_433_prometheus#6]
Hello,

I'm in the process of [packaging](https://github.com/NixOS/nixpkgs/pull/96511/files#diff-52d99641f05cd7caa2022a72371dcbc9R7) your exporter for NixOS since I find it useful – thanks for open-sourcing it!

It would be nice if at some point you could introduce a tag, say v0.1 – maybe once the tests are fixed, see #3. It's easier to reference short tags than ugly git sha1s.

Cheers,

**Comment by mhansen** [comment]
I think I figured out how to do this -- done! https://github.com/mhansen/rtl_433_prometheus/tree/v0.1

**Comment by mhansen** [comment]
btw NixOS is pretty cool and I'm stoked to hear this is being packaged :-)

**Comment by Zopieux** [comment]
Great to hear! Yeah, it can be a bit difficult to get started, but then you're hooked!

**Comment by Zopieux** [comment]
Just FYI this was merged moments ago, so your software is officially packaged for NixOS :-)

**Comment by mhansen** [comment]
That’s neat. Thanks for letting me know!
