### ISSUE TITLE
 Could not parse JSON, bad ID (expected float or string), got: <nil>

### ISSUE THREAD

**Issue by jsutch** [mhansen/rtl_433_prometheus#7]
rtl_433_prometheus_1  | 2020/09/28 23:35:13 channelMatchers: Hideki-TS04,3,Shed
rtl_433_prometheus_1  | 2020/09/28 23:35:13 idMatchers:
rtl_433_prometheus_1  | rtl_433 version 18.12-217-gcbbca50 branch master at 201905251412 inputs file rtl_tcp RTL-SDR
rtl_433_prometheus_1  | Trying conf file at "rtl_433.conf"...
rtl_433_prometheus_1  | Trying conf file at "/root/.config/rtl_433/rtl_433.conf"...
rtl_433_prometheus_1  | Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
rtl_433_prometheus_1  | Trying conf file at "/etc/rtl_433/rtl_433.conf"...
rtl_433_prometheus_1  |
rtl_433_prometheus_1  | 	Consider using "-M newmodel" to transition to new model keys. This will become the default someday.
rtl_433_prometheus_1  | 	A table of changes and discussion is at https://github.com/merbanan/rtl_433/pull/986.
rtl_433_prometheus_1  |
rtl_433_prometheus_1  | Registered 100 out of 127 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 62-63 67-71 73-100 102-103 108-116 119 121 124-127 ]
rtl_433_prometheus_1  | Found Rafael Micro R820T tuner
rtl_433_prometheus_1  | Exact sample rate is: 250000.000414 Hz
rtl_433_prometheus_1  | [R82XX] PLL not locked!
rtl_433_prometheus_1  | Sample rate set to 250000 S/s.
rtl_433_prometheus_1  | Tuner gain set to Auto.
rtl_433_prometheus_1  | Tuned to 433.920MHz.
rtl_433_prometheus_1  | Allocating 15 zero-copy buffers
rtl_433_prometheus_1  | Failed to allocate zero-copy buffer for transfer 0
rtl_433_prometheus_1  | Falling back to buffers in userspace
rtl_433_prometheus_1  | 2020/09/28 23:35:22 Could not parse JSON, bad ID (expected float or string), got: <nil>

And the command/docker dies.

the raw rtl_433 is dumping json from the command line. 
root@storage:/storage/prometheus/rtl_433_prometheus# rtl_433 -F json
rtl_433 version 20.02-65-g02a009c branch master at 202006142311 inputs file rtl_tcp RTL-SDR
Use -h for usage help and see https://triq.org/ for documentation.
Trying conf file at "rtl_433.conf"...
Trying conf file at "/root/.config/rtl_433/rtl_433.conf"...
Trying conf file at "/usr/local/etc/rtl_433/rtl_433.conf"...
Trying conf file at "/etc/rtl_433/rtl_433.conf"...
Registered 125 out of 153 device decoding protocols [ 1-4 8 11-12 15-17 19-21 23 25-26 29-36 38-60 63 67-71 73-100 102-105 108-116 119 121 124-128 130-149 151-153 ]
Found Rafael Micro R820T tuner
Exact sample rate is: 250000.000414 Hz
[R82XX] PLL not locked!
Sample rate set to 250000 S/s.
Tuner gain set to Auto.
Tuned to 433.920MHz.
{"time" : "2020-09-28 16:34:44", "model" : "Acurite-Tower", "id" : 15406, "channel" : "C", "battery_ok" : 1, "temperature_C" : 22.300, "humidity" : 55, "mic" : "CHECKSUM"}
{"time" : "2020-09-28 16:34:44", "model" : "Acurite-Tower", "id" : 15406, "channel" : "C", "battery_ok" : 1, "temperature_C" : 22.300, "humidity" : 55, "mic" : "CHECKSUM"}
...

Using this in the docker compose testing for one device:
root@storage:/storage/prometheus/rtl_433_prometheus# cat docker-compose.yml
version: '3.4'
services:
  rtl_433_prometheus:
    image: markhnsn/rtl_433_prometheus
    restart: always
    ports:
    - "9550:9550"
    devices:
    - "/dev/bus/usb"
    command: [
      "--subprocess", "/rtl_433 -F json",
      "--channel_matcher","Hideki-TS04,3,Test"
    ]

**Comment by mhansen** [comment]
Thanks for the bugreport. Looks like some rogue message came through
without an ID.

Some options:
Simplest: could you limit the device decoding protocols to only your
devices? this would ensure that only devices that have IDs get decoded.
e.g. in my docker-compose file, I pass:
      "--subprocess", "/rtl_433 -F json -R 19 -R 127 -R 40",
as arguments.

Harder: we could change the error handling to not simply quit the
application if we receive a message without an ID, but instead continue.
It's probably not worth crashing the application - it was just easier, as I
had Docker setup to auto-restart the app.

Actually, the second option doesn't sound that hard. I'll see if I can fix
it quickly

**Comment by jsutch** [comment]
that worked, thanks!

**Comment by mhansen** [comment]
Glad to hear (and glad to hear you're getting some use out of this code!)
Are you using it for anything cool? I'd love to hear :-)
